services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_server
    ports:
      - "5678:5678"
    environment:
      - WEBHOOK_URL=https://ec56-196-115-223-46.ngrok-free.app
      - TZ=Africa/Casablanca
      - N8N_RELEASE_TYPE=stable
    volumes:
      - ./n8n_data:/home/node/.n8n
